title: techematics
subtitle: Nico on math and programming
author: Nico Schlömer

# Use up-to-date minima for auto dark/light
# theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

# remote_theme: jekyll/minima
# minima:
#   skin: auto

# remote_theme: mmistakes/minimal-mistakes
# Liquid syntax error (line 15): Unknown tag 'include_cached' in
# /_layouts/default.html

# remote_theme: alshedivat/al-folio
# Invalid CSS after "...content-width: ": expected expression (e.g. 1px, bold),
# was ";" on line 4

# remote_theme: cotes2020/jekyll-theme-chirpy
# Build error:
# Liquid Exception: Liquid error
# (/tmp/jekyll-remote-theme-20231116-7-1dwm4gn/_includes/read-time.html line
# 3): wrong number of arguments (given 2, expected 1) included in
# /_layouts/post.html

email: nico.schloemer@gmail.com
# social links
twitter_username: nschloe
github_username: nschloe
# show_excerpts: true # set to false to remove excerpts on the homepage

markdown: kramdown
kramdown:
  math-engine: katex

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide
