title: Techematics
author: Nico
theme: minima
email: nico.schloemer@gmail.com
description: Nico's thoughts on math and programming
# social links
twitter_username: nschloe
github_username:  nschloe

show_excerpts: true # set to false to remove excerpts on the homepage
